close all;
clear; 
clc;

dataset_path = "Data";

snrs = linspace(5, -5, 5);
runs = 3;

for i = snrs
    sim = OFDM_System( ...
        OutputDir       = dataset_path, ...
        SNR             = i, ...  
        ChanModel       = "awgn", ... %"Model-A" "awgn"
        N               = 1024, ...
        L               = 64, ...
        ltf_sto_shift   = -32, ...
        Mod_pow         = 4, ...   
        Cod_rate        = 0.5, ...
        Bw              = 0.5, ... 
        Npil            = 8, ...
        data_Nsymb      = 1000, ...
        Fc              = 2.4e9, ...
        Fs              = 5e6, ...
        alpha           = 1.0, ...
        beta            = 0.1, ...
        DC_guard        = 32, ...
        sdr_order       = 0, ...
        check_crc       = 1 ...
    );

    sim.generate_dataset(runs);
    sim.run_channel_on_dataset();
    sim.process_dataset();
end