close all;
clear; 
clc;

dataset_path = "test";

snrs = 23:-1:17;
runs = 10;
k = 6;
bw = 1.0;

if exist(dataset_path, 'dir')
    rmdir(dataset_path, 's');
else
    disp(['Папка ', dataset_path, ' не существует.']);
end

for i = snrs
    sim = OFDM_System( ...
        OutputDir       = dataset_path, ...
        SNR             = i, ...  
        ChanModel       = "awgn", ... %"Model-A" "awgn"
        N               = 1024, ...
        L               = 64, ...
        ltf_sto_shift   = 0, ...
        Mod_pow         = k, ...   
        Cod_rate        = 0.5, ...
        Bw              = 0.5, ... 
        Npil            = 8, ...
        data_Nsymb      = 1000, ...
        Fc              = 2.4e9, ...
        Fs              = 5e6, ...
        alpha           = 0.0, ...
        beta            = 0.05, ...
        DC_guard        = 128, ...
        sdr_order       = 0, ...
        check_crc       = 1, ...
        graph_output    = 0, ...
        CFO             = 0, ...
        cfo_enable      = 1, ...
        ltf_eqv_enable  = 1, ...
        stf_est_symb    = 128, ...
        ltf_Nsymb       = 128 ...
    );

    sim.generate_dataset(runs);
    sim.run_channel_on_dataset();
    sim.process_dataset();

    k = sim.data_handler.Mod_pow;
    bw = (sim.data_handler.ofdm.Ndat+sim.data_handler.ofdm.Npil)/sim.data_handler.ofdm.N;
end


%NOT FOR PARAMETER CHANGING
sim = OFDM_System( ...
        OutputDir       = dataset_path, ...
        SNR             = 0, ...  
        ChanModel       = "awgn", ... %"Model-A" "awgn"
        N               = 1024, ...
        L               = 64, ...
        ltf_sto_shift   = 0, ...
        Mod_pow         = k, ...   
        Cod_rate        = 0.5, ...
        Bw              = 0.5, ... 
        Npil            = 8, ...
        data_Nsymb      = 1000, ...
        Fc              = 2.4e9, ...
        Fs              = 5e6, ...
        alpha           = 0.0, ...
        beta            = 0.0, ...
        DC_guard        = 128, ...
        sdr_order       = 0, ...
        check_crc       = 1, ...
        graph_output    = 0, ...
        CFO             = 0, ...
        cfo_enable      = 0, ...
        ltf_eqv_enable  = 1 ...
    );
bw = (sim.data_handler.ofdm.Ndat+sim.data_handler.ofdm.Npil)/sim.data_handler.ofdm.N;

filename = dataset_path+'/statistics.csv';
csv = readtable(filename, 'ReadRowNames', true);

data = csv(csv.Var1==k,:);
data = data(1:length(data.Var1)-mod(length(data.Var1), runs), :);

rmse = -db(mean(reshape(data.Var8, runs, [])));
snrs = mean(reshape(data.Var2, runs, []));


figure(3);
clf;
t_ber = (berawgn(snrs-10*log10(k)-10*log10(bw), 'qam', 2^k));
semilogy(snrs, t_ber, "LineStyle","-.");
hold;

id_ber = (mean(reshape(data.Var6, runs, [])));
scatter(snrs, id_ber, 20, "green", "filled");

ber = mean((reshape(data.Var4, runs, [])));
error = std(reshape(data.Var4, runs, []), 0, 1);

errorbar(snrs, ber, error, "x", Color="red", DisplayName="QAM4");

legend("QAM4","QAM4","QAM4");
grid on;
xlabel("SNR");
ylabel("BER");


