close all;
clear; 
% clc;

dataset_path = "Datasets";


sim = OFDM_System( ...
    OutputDir       = dataset_path, ...
    SNR             = 15, ...  
    ChanModel       = "Model-F", ... %"Model-A" "awgn"
    N               = 1024, ...
    L               = 64, ...
    ltf_sto_shift   = -32, ...
    Mod_pow         = 4, ...   
    Cod_rate        = 0.5, ...
    Bw              = 0.25, ... 
    Npil            = 16, ...
    pilAmpl         = 4.0, ...
    data_Nsymb      = 500, ...
    Fc              = 2.8e9, ...
    Fs              = 5e6, ...
    alpha           = 1.0, ...
    beta            = 0.05, ...
    cfo_enable      = 1.0, ...
    DC_guard        = 32, ...
    sdr_order       = 1, ...
    check_crc       = 1, ...
    graph_output    = 1, ...
    stf_est_symb    = 128, ...
    ltf_Nsymb       = 128, ...
    win_slope       = 0, ...
    soft            = 1 ...
);

% sim.generate_dataset(10);
% sim.run_channel_on_dataset();
% sim.run_sdr_channel_on_dataset();
sim.process_dataset();


fprintf("\n");