close all;
clear; 
% clc;

dataset_path = "Datasets";


sim = test( ...
    OutputDir       = dataset_path, ...
    SNR             = 10, ...  
    ChanModel       = "awgn", ... %"Model-A" "awgn"
    N               = 1024, ...
    L               = 64, ...
    ltf_sto_shift   = -32, ...
    h_len           = 16, ...
    Mod_pow         = 2, ...   
    Cod_rate        = 0.5, ...
    Bw              = 0.5, ... 
    Npil            = 16, ...
    virt_pil        = 32, ...
    pilAmpl         = 4.0, ...
    data_Nsymb      = 2000, ...
    Fc              = 2.8e9, ...
    Fs              = 5e6, ...
    sdr_gain        = 2^9, ...
    alpha           = 0.2, ...
    beta            = 0.2, ...
    cfo_enable      = 1.0, ...
    DC_guard        = 64, ...
    sdr_order       = 0, ...
    check_crc       = 1, ...
    graph_output    = [2,3,5], ...
    stf_est_symb    = 128, ...
    ltf_Nsymb       = 128, ...
    win_slope       = 0, ...
    est_method      = "LS", ...
    metric          = "ML", ...
    soft            = 1 ...
);

% sim.generate_dataset(10, "seed", [1,2,3,4,5]);
% sim.generate_dataset(1);
% sim.run_channel_on_dataset();
% sim.run_sdr_channel_on_dataset();
sim.process_dataset();


fprintf("\n");
